//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionFichesClients.FichesClientsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FicheClient", Namespace="http://schemas.datacontract.org/2004/07/FichesClientWCFService")]
    [System.SerializableAttribute()]
    public partial class FicheClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexe {
            get {
                return this.SexeField;
            }
            set {
                if ((object.ReferenceEquals(this.SexeField, value) != true)) {
                    this.SexeField = value;
                    this.RaisePropertyChanged("Sexe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FichesClientsService.IFichesClientService")]
    public interface IFichesClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/GetFiches", ReplyAction="http://tempuri.org/IFichesClientService/GetFichesResponse")]
        GestionFichesClients.FichesClientsService.FicheClient[] GetFiches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/GetFiches", ReplyAction="http://tempuri.org/IFichesClientService/GetFichesResponse")]
        System.Threading.Tasks.Task<GestionFichesClients.FichesClientsService.FicheClient[]> GetFichesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/GetFichesClientsMasculins", ReplyAction="http://tempuri.org/IFichesClientService/GetFichesClientsMasculinsResponse")]
        GestionFichesClients.FichesClientsService.FicheClient[] GetFichesClientsMasculins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/GetFichesClientsMasculins", ReplyAction="http://tempuri.org/IFichesClientService/GetFichesClientsMasculinsResponse")]
        System.Threading.Tasks.Task<GestionFichesClients.FichesClientsService.FicheClient[]> GetFichesClientsMasculinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/AjoutFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/AjoutFicheClientResponse")]
        bool AjoutFicheClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/AjoutFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/AjoutFicheClientResponse")]
        System.Threading.Tasks.Task<bool> AjoutFicheClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/SuppressionFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/SuppressionFicheClientResponse")]
        bool SuppressionFicheClient(GestionFichesClients.FichesClientsService.FicheClient fiche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/SuppressionFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/SuppressionFicheClientResponse")]
        System.Threading.Tasks.Task<bool> SuppressionFicheClientAsync(GestionFichesClients.FichesClientsService.FicheClient fiche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/ModificationFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/ModificationFicheClientResponse")]
        bool ModificationFicheClient(GestionFichesClients.FichesClientsService.FicheClient fiche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFichesClientService/ModificationFicheClient", ReplyAction="http://tempuri.org/IFichesClientService/ModificationFicheClientResponse")]
        System.Threading.Tasks.Task<bool> ModificationFicheClientAsync(GestionFichesClients.FichesClientsService.FicheClient fiche);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFichesClientServiceChannel : GestionFichesClients.FichesClientsService.IFichesClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FichesClientServiceClient : System.ServiceModel.ClientBase<GestionFichesClients.FichesClientsService.IFichesClientService>, GestionFichesClients.FichesClientsService.IFichesClientService {
        
        public FichesClientServiceClient() {
        }
        
        public FichesClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FichesClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FichesClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FichesClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionFichesClients.FichesClientsService.FicheClient[] GetFiches() {
            return base.Channel.GetFiches();
        }
        
        public System.Threading.Tasks.Task<GestionFichesClients.FichesClientsService.FicheClient[]> GetFichesAsync() {
            return base.Channel.GetFichesAsync();
        }
        
        public GestionFichesClients.FichesClientsService.FicheClient[] GetFichesClientsMasculins() {
            return base.Channel.GetFichesClientsMasculins();
        }
        
        public System.Threading.Tasks.Task<GestionFichesClients.FichesClientsService.FicheClient[]> GetFichesClientsMasculinsAsync() {
            return base.Channel.GetFichesClientsMasculinsAsync();
        }
        
        public bool AjoutFicheClient() {
            return base.Channel.AjoutFicheClient();
        }
        
        public System.Threading.Tasks.Task<bool> AjoutFicheClientAsync() {
            return base.Channel.AjoutFicheClientAsync();
        }
        
        public bool SuppressionFicheClient(GestionFichesClients.FichesClientsService.FicheClient fiche) {
            return base.Channel.SuppressionFicheClient(fiche);
        }
        
        public System.Threading.Tasks.Task<bool> SuppressionFicheClientAsync(GestionFichesClients.FichesClientsService.FicheClient fiche) {
            return base.Channel.SuppressionFicheClientAsync(fiche);
        }
        
        public bool ModificationFicheClient(GestionFichesClients.FichesClientsService.FicheClient fiche) {
            return base.Channel.ModificationFicheClient(fiche);
        }
        
        public System.Threading.Tasks.Task<bool> ModificationFicheClientAsync(GestionFichesClients.FichesClientsService.FicheClient fiche) {
            return base.Channel.ModificationFicheClientAsync(fiche);
        }
    }
}
